config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/index', to: 'static_pages#index'
  get '/home', to: 'static_pages#home'
  get '/howitswork', to: 'static_pages#howitswork'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  get 'users/:id/orders' => 'users#orders', :as => :user_orders
  get 'users/:id/proposals' => 'users#proposals', :as => :user_proposals
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :categories
  resources :orders
  resources :proposals
  delete 'choose_proposal' => 'proposals#choose_proposal', :as => :choose_proposal
  patch '/orders/:id/finish_order' => 'orders#finish_order', :as => :finish_order
  # resources :responses, only: [:new, :create]
  resources :responses
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :proposals, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_one_attached :avatar
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest

  validates :first_name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :last_name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :city, presence: true, length: { minimum: 3, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_secure_password

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def feed
    Order.where("user_id = ?", id)
  end 

  private
  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index edit update destroy orders proposals]
  before_action :correct_user, only: %i[edit update orders orders proposals]
  before_action :admin_user, only: :destroy

  def index
    @users = if current_user.admin?
               User.paginate(page: params[:page])
             else
               User.where(activated: true).paginate(page: params[:page])
             end
    @users = @users.where(" ' ' || lower(first_name) || ' ' || lower(last_name) || ' ' LIKE ?", "%#{params[:search].downcase}%").paginate(page: params[:page]) if params[:search]
  end

  def show
    @user = User.find(params[:id])
    @responses = Response.where('user_id = ?', @user.id).paginate(page: params[:page])
    redirect_to root_url && return unless User.where(activated: true)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.avatar.attach(params[:avatar])
    if @user.save
      if @user.send_activation_email
      flash[:info] = 'Перевір пошту для активації аккаунту'
      redirect_to root_url
      else
        @user.destroy
        flash[:info] = 'Проблеми з надсиланням листа. Попробуй зареєструватись пізніше.'
        redirect_to root_url
      end
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'Профіль оновлено'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'Користувача видалено'
    redirect_to users_url
  end

  def orders
    @user = User.find(params[:id])
    if params[:status] == 'Активне'
      @orders = @user.orders.where('status = ? and duedate >=?', params[:status], Time.now).paginate(page: params[:page], per_page: 20)
    elsif params[:status] == 'Виконується' || params[:status] == 'Завершене'
      @orders = @user.orders.where('status = ?', params[:status]).paginate(page: params[:page], per_page: 20)
    elsif params[:status] == 'Незавершене'
      @orders = @user.orders.where('duedate < ?', Time.now).paginate(page: params[:page], per_page: 20)
    else
      @orders = @user.orders.where('status = ? and duedate >=?', 'Активне', Time.now).paginate(page: params[:page], per_page: 20)
    end
    if params[:is_used] == "true" && (params[:title_or_description] || params[:category_id] || params[:city] || params[:min_price] || params[:max_price] || params[:status])
      @orders = @orders.search_by(params[:title_or_description],
                                       params[:category_id],
                                       params[:city],
                                       params[:min_price],
                                       params[:max_price]).paginate(page: params[:page], per_page: 20)
    end
  end

  def proposals
    @user = User.find(params[:id])
    @proposals = @user.proposals.paginate(page: params[:page], per_page: 20)
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :city,
      :description,
      :password,
      :password_confirmation,
      :avatar
    )
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 160 })
    size = options[:size]
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.first_name, class: 'gravatar')
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> 

      <%= f.label :first_name, 'Ім\'я' %>
      <%= f.text_field :first_name, class: 'form-control'  %>

      <%= f.label :last_name, 'Прізвище' %>
      <%= f.text_field :last_name, class: 'form-control'  %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control'  %>

      <%= f.label :city, 'Місто' %>
      <%= f.text_field :city, class: 'form-control'  %>

      <%= f.label :description, 'Опис' %>
      <%= f.text_area :description, class: 'form-control'  %>

      <%= f.label :password, 'Пароль' %>
      <%= f.password_field :password, class: 'form-control'  %>

      <%= f.label :password_confirmation, 'Підтвердження пароля' %>
      <%= f.password_field :password_confirmation, class: 'form-control'  %>
      <%= f.label "Фото профілю"%>
      <%= f.file_field :avatar%>

      <%= f.submit yield(:text_button), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li class= "item">
  <div class="information">
    <div class="information_main">
      <% if user.avatar.attached? %>
        <image src="<%=(url_for(user.avatar))%>" style=" width:64px;">
      <% else %>
        <span><%= gravatar_for(user, size: 64) %></span>
      <% end %>
      <%= link_to "#{user.first_name} #{user.last_name}", user, class:"user_link" %>
    </div>
    <% if current_user.admin?%>
    <div class="information_add">
      <span class="activated">
        <%if user.activated %>
          Підтверджений: Так
        <% else %>
        Підтверджений: Ні
        <% end %>
      </span>
      <span class="admin">
        <%if user.admin? %>
          Адміністратор: Так
        <% else %>
          Адміністратор: Ні
        <% end %>
      </span>
    </div>
    <% end %> 
  </div>
  <div class="buttons">
  <% if current_user.admin? && !current_user?(user) %>
      <%= link_to 'Видалити', user, method: :delete, data: { confirm: "Ти впевнений?"}, class: "btn btn-danger" %>
  <% end %> 
  </div>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Редагування профілю') %>
<% provide(:text_button, 'Змінити') %>

<div class="signup">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">      
      <h1>Редагування профілю</h1>
      <%= render 'form' %>
      <%# <div class="gravater_edit">
        <%= gravatar_for @user %>
        <%# <a href="https://gravatar.com/emails" target="_blank">Змінити</a> %>
      <%# </divЮ %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Всі користувачі') %>
<div class="users">
<h1>Всі користувачі</h1>
    <%= form_for users_path, method: :get do %>
  <div class="search">
    <div class="input">
      <%= text_field_tag :search, params[:search], placeholder: "Пошук...", class: 'form-control' %>
    </div>
    <div class="button">
      <%= button_tag('Шукати',name: nil, class: 'btn btn-info')%>
    </div>
  </div>
    <% end %>
  <ul class="items">
    <%= render @users%>
  </ul>
<%= will_paginate%>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Реєстрація') %>
<% provide(:text_button, 'Зареєструвати') %>

<div class="signup">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">      
      <h1>Реєстрація</h1>

      <%= render 'form'%>
    </div>
  </div>
</div>

app/views/users/orders.html.erb
<% provide(:title, 'Мої замовлення') %>


<div class="orders">
  <h1>Мої замовлення (<%= @user.orders.count %>) </h1>
  <div class="orders_buttons">
    <%= link_to 'Додати', new_order_path, class: "btn btn-lg btn-success button_class" %>
    <%= link_to 'Активні', user_orders_path(current_user, status: 'Активне'), class: "btn btn-lg btn-primary button_class" %>
    <%= link_to 'Виконуються', user_orders_path(current_user, status: 'Виконується'), class: "btn btn-lg btn-warning button_class" %>
    <%= link_to 'Завершені', user_orders_path(current_user, status: 'Завершене'), class: "btn btn-lg btn-info button_class" %>
    <%= link_to 'Незавершені', user_orders_path(current_user, status: 'Незавершене'), class: "btn btn-lg btn-danger button_class" %>
  </div>
  <div class="row">
    <div class="col-md-3 col-sm-3">
      <div class="filter ">
        <h2>Пошук</h2>
        <%= form_for "", url: user_orders_path(current_user), role: "search", method: :get do %>
        <%= hidden_field_tag :status, params[:status] %>
        <%= hidden_field_tag :is_used, true %>
        <h4>Категорія</h4>
        <%= select_tag 'category_id', options_for_select(Category.all.collect {|x| [x.title, x.id]}), placeholder: "Введіть категорію", class: 'form-control' %>
        <h4>Назва</h4>
        <%= text_field_tag :title_or_description, @title_or_description, placeholder: "Пошук...", class: 'form-control' %>
        <h4>Адреса</h4>
        <%= text_field_tag :city, @city, placeholder: "Введіть адресу", class: 'form-control' %>
        <h4>Ціна</h4>
        <div class="price" style="display:flex;">
        <%= text_field_tag :min_price, @min_price, placeholder: "Від", type: "number", :value => 0, class: 'form-control', style: "width:45%;" %><span style="width:20px; text-align:center;">-</span>
        <%= text_field_tag :max_price, @max_price, placeholder: "До", type: "number", class: 'form-control', style: "width:45%;" %>
        </div>
        

        <%= button_tag 'Шукати', type: 'куіуе', class: "btn btn-info" %>
        <% end %>
        </div>
    </div>
    <div class="col-md-9 col-sm-9">
      <ul class="items">
        <%= render @orders%>
      </ul>
    </div>
    </div>
  </div>

<%= will_paginate @orders%>
</div>

app/views/users/proposals.html.erb
<% provide(:title, 'Мої заявки') %>


<div class="proposals">
  <h1>Мої заявки (<%= @user.proposals.count %>) </h1>
  <%# <%= link_to 'Активні', '#', class: "btn-lg btn-primary button_class" %>
  <%# <%= link_to 'Виконуються', '#', class: "btn-lg btn-warning button_class" %>
  <%# <%= link_to 'Завершені', '#', class: "btn-lg btn-info button_class" %>

<%= will_paginate @proposals%>

<ol class="items">
  <% @proposals.each do |proposal| %>
  <li id="proposal-<%= proposal.id %>" class="item">
  <div class="row">
    <div class="col-md-1">
      <div class="gravatar-div">
        <% if @user.avatar.attached? %>
          <image src="<%=(url_for(@user.avatar))%>" style=" width:80px;">
        <% else %>
          <%= link_to gravatar_for(proposal.user, size: 80), proposal.user %>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">
      <div class="text">
        <span class="user">
          <%= link_to "#{proposal.order.title}", proposal.order, class: "user_link" %>
        </span> 
        <span class="content">
          <%= proposal.content %>
        </span>
      </div>
    </div>
    <div class="col-md-3">
      <div class="data">
        <span class="element"> 
          <b>Ціна:</b> <%= proposal.price %>
        </span>
        <span class="element"> 
          <b>Створено:</b> <%= proposal.created_at.strftime("%d.%m.%Y %H:%M") %>
        </span>
        <span class="element"> 
          <b>Завершити до:</b> <%= proposal.duedate.strftime("%d.%m.%Y %H:%M") %>
        </span>
        <div class="buttons">
          <% if current_user && current_user?(proposal.user) &&['Активне', 'Незавершене'].include?(proposal.order.status) %> 
            <%= link_to "Видалити", proposal, method: :delete, data: { confirm: "Ти впевнений?" }, class: "btn btn-danger" %>
            <%= link_to "Редагувати", edit_proposal_path(proposal.id), class: "btn btn-warning" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li> 
  <% end %>
</ol>

<%= will_paginate @proposals%>
</div>

app/views/users/show.html.erb
<% provide(:title, "#{@user.first_name} #{@user.last_name}")%>

<div class="profile">
  <div class="row">
    <div class="col-lg-3 col-md-3 col-sm-3">
      <div class="profile_main">
        <% if @user.avatar.attached? %>
          <image src="<%=(url_for(@user.avatar))%>" style=" width:230px;">
          <% else %>
          <span><%= gravatar_for(@user, size: 160) %></span>
        <% end %>
        <div class="email"><%= @user.email %></div>
        <div class="city"><%= @user.city %></div>
        <div class="created_at"> На сайті з <%= @user.created_at.strftime("%d.%m.%Y %H:%M") %></div>
      </div>
    </div>
    <div class="col-lg-9 col-md-9 col-sm-8">
      <h1 class="name"><%= @user.first_name %> <%= @user.last_name %></h1>
      <% if @user.responses.any? %>
      <h3>Рейтинг: <%=(@user.responses.sum(:score).to_f / @user.responses.count).floor(1) %></h3>
      <% end %>
      <div class="description">
        <%= @user.description %>
      </div>
    </div>
  </div>
</div>
<div class="responses">
  <% if @user.responses.any? %>
  <h3>Відгуки (<%= @user.responses.count %>)</h3>
  <ol class="items">
    <%= render @responses %>
  </ol>
  <%= will_paginate @responses %>
  <% end %>
</div>