config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/index', to: 'static_pages#index'
  get '/home', to: 'static_pages#home'
  get '/howitswork', to: 'static_pages#howitswork'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  get 'users/:id/orders' => 'users#orders', :as => :user_orders
  get 'users/:id/proposals' => 'users#proposals', :as => :user_proposals
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :categories
  resources :orders
  resources :proposals
  delete 'choose_proposal' => 'proposals#choose_proposal', :as => :choose_proposal
  patch '/orders/:id/finish_order' => 'orders#finish_order', :as => :finish_order
  # resources :responses, only: [:new, :create]
  resources :responses
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :proposals, dependent: :destroy
  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 5000 }
  validates :city, presence: true
  validates :price, presence: true, numericality: {message: 'є неправильним значенням' }
  validates_datetime :duedate, on_or_after: lambda { Time.current }

  def self.search_by(title_or_description, category_id, city, min_price, max_price)
    min_price = -1 if min_price.empty?
    max_price = 1_000_000_000 if max_price.empty?
    title_or_description = ' ' if title_or_description.empty?
    city = ' ' if city.empty?
    # where('"category_id = '#{category_id}' AND 
      # (LOWER(title) LIKE '%#{title_or_description.downcase}%' OR 
      # (LOWER(description) LIKE '%#{title_or_description.downcase}%' AND 
      # (LOWER(city) LIKE '%#{city.downcase}%' AND 
      # price >= #{min_price} AND price <= #{max_price} "')
    where("category_id = ? AND (' ' || LOWER(title) || ' ' LIKE ? OR ' ' || LOWER(description) || ' ' LIKE ?) AND ' ' || city || ' ' LIKE ? AND price >= ? AND price <= ?", category_id, "%#{title_or_description.downcase}%", "%#{title_or_description.downcase}%", "%#{city.downcase}%", min_price, max_price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :logged_in_user, only: %i[create destroy]
  before_action :correct_user, only: %i[destroy edit update]
  before_action :status_check

  def status_check
    @orders = Order.where('status = ? and duedate < ?', 'Активне', Time.now)
    @orders.each do |order|
      order.update_attribute('status', 'Незавершене')
    end
  end

  def index
    if current_user.nil?
      @orders = Order.where('status = ?', 'Активне').paginate(page: params[:page])
    else
      @orders = Order.where('status = ? and duedate >= ? and user_id != ?', 'Активне', Time.now, current_user.id).paginate(page: params[:page])
      @orders = Order.where('user_id != ?', current_user.id).paginate(page: params[:page]) if current_user.admin?
    end
    if (params[:title_or_description] || params[:id] || params[:city] || params[:min_price] || params[:max_price])
      @orders = @orders.search_by(params[:title_or_description],
                                  params[:id],
                                  params[:city],
                                  params[:min_price],
                                  params[:max_price])
    end
  end

  def show
    @order = Order.find(params[:id])
    @proposals = @order.proposals.paginate(page: params[:page])
  end

  def new
    @order = current_user.orders.build if logged_in?
  end

  def create
    @order = current_user.orders.build(order_params)
    @order.status = 'Активне'
    if @order.save
      flash[:success] = "Замовлення створено!"
      redirect_to orders_url(current_user)
    else
      render 'new'
    end
  end

  def edit
      if current_user.admin?
        @order = Order.find_by(id: params[:id])
      else
        @order = current_user.orders.find_by(id: params[:id])
        if ['Виконується', 'Завершене'].include?(@order.status)
          flash[:success] = 'Замовлення виконується/завершене'
          redirect_to order_url
        end
      end
  end

  def update
    if current_user.admin?
      @order = Order.find_by(id: params[:id])
    else
      @order = current_user.orders.find_by(id: params[:id])
    end
    @order.status = 'Активне'
    if @order.update(order_params)
      flash[:success] = 'Дані замовлення оновлено'
      redirect_to order_url
    else
      render 'edit'
    end
  end

  def destroy
    @order.destroy
    flash[:success] = 'Замовлення видалено'
    redirect_to orders_url(current_user)
  end

  def finish_order
    @order = Order.find(params[:id])
    @order.update_attribute(:status, 'Завершене')
    redirect_to @order
  end

  private

  def admin_user
    redirect_to(root_url) unless current_user.try(:admin?)
  end

  def order_params
    params.require(:order).permit(
      :title,
      :description,
      :skills,
      :city,
      :duedate,
      :category_id,
      :price,
      :status
    )
  end

  # def category_params
  #   params.require(:category).permit(:category_id)
  # end

  # def correct_user
  #   @order = current_user.orders.find_by(id: params[:id])
  #   redirect_to orders_url(current_user) if @order.nil?
  # end

  def correct_user
    if current_user.admin?
      @order = Order.find_by(id: params[:id])
    else
      @order = current_user.orders.find_by(id: params[:id])
    end
    redirect_to orders_url(current_user) if @order.nil?
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order.html.erb
<li id="order-<%= order.id %>" class="item">
  <div class="row">
    <div class="col-lg-10 col-md-10">
      <div class="text">
        <span class="text_item title">
          <%= link_to order.title, order, class: "link" %>
        </span>
        <span class="text_item"> 
          <b>Місто:</b> <%= order.city %>
        </span>
        <span class="text_item"> 
          <b>Створено:</b> <%= order.created_at.strftime("%d.%m.%Y %H:%M") %>
        </span>
        <span class="text_item"> 
          <b>Завершується:</b> <%= order.duedate.strftime("%d.%m.%Y %H:%M") %>
        </span>
        <span class="text_item">
          <b>Категорія:</b> <%= order.category.title %>
        </span>
        <span class="text_item">
          <b>Статус:</b> <%= order.status %>
        </span>
      </div>
    </div>
    <div class="col-lg-2 col-md-2">
      <div class="buttons">
      <span class="money">
          <b>Бюджет:</b> <%= order.price %> ₴
      </span>
        <% if (current_user && (current_user?(order.user) || current_user.admin?)  && (['Активне', 'Незавершене', 'Завершене'].include?(order.status)))%> 
          <%= link_to "Видалити", order, method: :delete, data: { confirm: "Ти впевнений?" }, class: "btn btn-danger" %>
        <% end %>
        <% if (current_user && (current_user?(order.user) || current_user.admin? ) && (['Активне', 'Незавершене'].include?(order.status)))%>
          <%= link_to "Редагувати", edit_order_path(order.id), class: "btn btn-warning" %>
        <%end%>
        <% if current_user && (current_user?(order.user) || current_user.admin? ) && (['Виконується'].include?(order.status))%>
          <%= link_to "Завершити", finish_order_path(order.id), method: :patch, class: "btn btn-primary" %>
        <%end%>
      </div>
    </div>
  </div>
</li> 

app/views/orders/_order_form.html.erb
<%= form_with(model: @order, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <%= f.label :title, 'Назва' %>
  <%= f.text_field :title, class: 'form-control'  %>
  
  <%= f.label :description, 'Опис' %>
  <%= f.text_area :description %>

  <%= f.label :skills, 'Навички' %>
  <%= f.text_field :skills %>

  <%= f.label :city, 'Місцезнаходження' %>
  <%= f.text_field :city, class: 'form-control'  %>

  <%= f.label :duedate, 'Дата завершення' %>
  <%= f.datetime_select :duedate, class: 'form-control datetime'%>

  <%= f.label :category_id, 'Категорія' %>
  <%= f.select :category_id, Category.all.collect {|x| [x.title, x.id]} %>

  <%= f.label :price, 'Бюджет ₴' %>
  <%= f.text_field :price, type: "number", style: "width: 90%; margin-right:20px;" %>

  <%= f.submit yield(:text_button), class: "btn btn-primary" %>
<% end %>

app/views/orders/edit.html.erb
<% provide(:title, 'Редагування замовлення') %>
<% provide(:text_button , 'Змінити') %>
<div class="order_form">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">      
      <h1>Редагування даних замовлення</h1>
      <%= render 'order_form' %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<% provide(:title, 'Всі замовлення') %>


<div class="orders">
  <h1>Всі замовлення</h1>
  <div class="orders_buttons">
  <% if logged_in? %>
  <%= link_to 'Мої замовлення', user_orders_path(current_user), class: "btn btn-lg btn-info button_class" %>
  <%= link_to 'Додати замовлення', new_order_path, class: "btn btn-lg btn-success button_class" %>
  <% end %>
  </div>
  <div class="orders_main">
    <div class="row">
      <div class="col-md-3 col-sm-3">
        <div class="filter ">
          <h2>Пошук</h2>
          <%= form_for "", url: orders_path, role: "search", method: :get do %>
          <h4>Категорія</h4>
          <%= select_tag 'id', options_for_select(Category.all.collect {|x| [x.title, x.id]}), placeholder: "Введіть категорію", class: 'form-control' %>
          <h4>Назва</h4>
          <%= text_field_tag :title_or_description, @title_or_description, placeholder: "Пошук...", class: 'form-control' %>
          <h4>Адреса</h4>
          <%= text_field_tag :city, @city, placeholder: "Введіть адресу", class: 'form-control' %>
          <h4>Ціна</h4>
          <div class="price" style="display:flex;">
          <%= text_field_tag :min_price, @min_price, placeholder: "Від", type: "number", :value => 0, class: 'form-control', style: "width:45%;" %><span style="width:20px; text-align:center;">-</span>
          <%= text_field_tag :max_price, @max_price, placeholder: "До", type: "number", class: 'form-control', style: "width:45%;" %>
          </div>
          

          <%= button_tag 'Шукати', type: 'куіуе', class: "btn btn-info search_btn" %>
          <% end %>
          </div>
      </div>
      <div class="col-md-9 col-sm-9">
        <ul class="items">
          <%= render @orders%>
          <%= will_paginate%>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<% provide(:title, 'Створити замовлення') %>
<% provide(:text_button , 'Створити') %>

<div class="create_order">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">      
      <h1>Створити замовлення</h1>

      <%= render 'order_form'%>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<% provide(:title, "#{@order.title}")%>

<div class="order-more">
  <div class="row">
    <div class="col-md-8 col-sm-8">
      <span class="title">
        <%= @order.title %>
      </span>
    </div>
    <div class="col-md-4 col-sm-4">
      <span class="price">
        <%= @order.price %> ₴
      </span>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="data">
        <div class="labell">
          Категорія: <%= @order.category.title %>
        </div>
        <div class="labell">
          Опис
        </div>
        <div class="description">
          <%= @order.description %>
        </div>
        <div class="labell">
          Навички
        </div>
        <div class="skills">
          <%= @order.skills %>
        </div>
      </div>
      <div class="extended-data">
        <span class="item"> 
          <b>Місто:</b> <%= @order.city %>
        </span>
        <span class="item"> 
          <b>Створено:</b> <%= @order.created_at.strftime("%d.%m.%Y %H:%M") %>
        </span>
        <span class="item"> 
          <b>Завершується:</b> <%= @order.duedate.strftime("%d.%m.%Y %H:%M") %>
        </span>
        <span class="item"> 
          <b>Статус:</b> <%= @order.status %>
        </span>
      </div>
      <div class="user_info">
        <span class="item llabel">Про замовника</span>
        <span class="item"><%= link_to "#{@order.user.first_name} #{@order.user.last_name}", @order.user, class: "llabel_link_profile" %></span>
        <span class="item"><b>Email:</b> <%= @order.user.email %></span>
        <span class="item"><b>Рейтинг: </b> <%= (@order.user.responses.sum(:score).to_f / @order.user.responses.count).floor(1) %></span>
      </div>
    </div>
  </div>
      
</div>
<div class="menu">
      <div class="buttons">
      <% if current_user && (current_user?(@order.user) || current_user.admin?)  && (['Активне', 'Незавершене', 'Завершене'].include?(@order.status))%> 
          <%= link_to "Видалити", @order, method: :delete, data: { confirm: "Ти впевнений?" }, class: "btn btn-danger" %>
        <% end %>
        <% if current_user && (current_user?(@order.user) || current_user.admin? ) && (['Активне', 'Незавершене'].include?(@order.status))%>
          <%= link_to "Редагувати", edit_order_path(@order.id), class: "btn btn-warning" %>
        <%end%>
        <% if current_user && !(current_user?(@order.user)) && (['Активне'].include?(@order.status))%> 
          <%= link_to "Подати заявку", new_proposal_path(order_id: @order.id), class: "btn btn-success" %>
        <% end %>
        <% if current_user && (current_user?(@order.user) || current_user.admin? ) && (['Виконується'].include?(@order.status))%>
          <%= link_to "Завершити", finish_order_path(@order.id), method: :patch, class: "btn btn-primary" %>
        <%end%>
      </div>
</div>
<div class="proposals">
      <div class="row">
        <div class="col-md-12">
          <% if @order.proposals.any? %>
            <h3><%= info_about_proposals(@order.status) %></h3>
            <ol class="items">
              <%= render @proposals %>
            </ol>
            <%= will_paginate @proposals %> 
          <% end %>
        </div>
      </div>
</div>