config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/index', to: 'static_pages#index'
  get '/home', to: 'static_pages#home'
  get '/howitswork', to: 'static_pages#howitswork'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  get 'users/:id/orders' => 'users#orders', :as => :user_orders
  get 'users/:id/proposals' => 'users#proposals', :as => :user_proposals
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :categories
  resources :orders
  resources :proposals
  delete 'choose_proposal' => 'proposals#choose_proposal', :as => :choose_proposal
  patch '/orders/:id/finish_order' => 'orders#finish_order', :as => :finish_order
  # resources :responses, only: [:new, :create]
  resources :responses
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :user
  belongs_to :order
  has_one :response, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :order_id, presence: true
  validates :content, length: { maximum: 5000 }
  validates :price, presence: true, numericality: {message: 'є неправильним значенням' }
  validates_datetime :duedate, on_or_after: lambda { Time.current }
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :logged_in_user, only: %i[create destroy]
  before_action :correct_user, only: %i[destroy update edit]

  def new
    if current_user.proposals.find_by(order_id: params[:order_id])
      flash[:success] = "Заявку вже подано!"
      redirect_to user_proposals_url(current_user)
    else
      @proposal = current_user.proposals.build(order_id: params[:order_id]) if logged_in?
    end
  end

  def create
    @proposal = current_user.proposals.build(proposals_params)
    if @proposal.save
      flash[:success] = "Заявку створено!"
      redirect_to user_proposals_url(current_user)
    else
      render 'new'
    end
  end

  def edit
    @proposal = current_user.proposals.find_by(id: params[:id])
  end

  def update
    if @proposal.update(proposals_params)
      flash[:success] = 'Дані заявки оновлено'
      redirect_to user_proposals_url(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    @proposal.destroy
    flash[:success] = 'Заявку видалено'
    redirect_to request.referrer || proposals_url(current_user)
  end

  def choose_proposal
    @proposal = Proposal.find_by(id: params[:id])
    @order = Order.find_by(id: @proposal.order_id)
    proposals = Proposal.where('order_id = ? and id != ?', @proposal.order_id, @proposal.id)
    proposals.each do |proposal|
      proposal.destroy
    end
    @order.status = 'Виконується'
    @order.save
    redirect_to request.referrer || orders_url(current_user)
  end

  private

    def proposals_params
      params.require(:proposal).permit(
        :content,
        :price,
        :duedate,
        :order_id
      )
    end

    def correct_user
      if current_user.admin?
        @proposal = Proposal.find_by(id: params[:id])
      else
        @proposal = current_user.proposals.find_by(id: params[:id])
      end
      redirect_to user_proposals_url(current_user) if @proposal.nil?
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_proposal.html.erb
<li id="proposal-<%= proposal.id %>" class="item">
  <div class="row">
    <div class="col-md-1">
      <div class="gravatar-div">
        <% if proposal.user.avatar.attached? %>
          <image src="<%=(url_for(proposal.user.avatar))%>" style=" width:80px;">
        <% else %>
          <%= link_to gravatar_for(proposal.user, size: 80), proposal.user %>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">
      <div class="text">
        <span class="user">
          <%= link_to "#{proposal.user.first_name} #{proposal.user.last_name}", proposal.user, class: "user_link" %>
        </span> 
        <span class="content">
          <%= proposal.content %>
        </span>
      </div>
    </div>
    <div class="col-md-3">
      <div class="data">
        <span class="element"> 
          <b>Ціна:</b> <%= proposal.price %>
        </span>
        <span class="element"> 
          <b>Створено:</b> <%= proposal.created_at.strftime("%d.%m.%Y %H:%M") %>
        </span>
        <span class="element"> 
          <b>Завершити до:</b> <%= proposal.duedate.strftime("%d.%m.%Y %H:%M") %>
        </span>
        <div class="buttons">
          <% if current_user && (current_user?(proposal.user) || current_user.admin?) && (['Активне'].include?(@order.status)) %> 
            <%= link_to "Видалити", proposal, method: :delete, data: { confirm: "Ти впевнений?" }, class: "btn btn-danger" %>
            <%= link_to "Редагувати", edit_proposal_path(proposal.id), class: "btn btn-warning" %>
          <% end %>
          <% if current_user && (current_user?(@order.user) || current_user.admin?) && @order.status == 'Активне' %>
            <%= link_to "Вибрати", choose_proposal_path(id: proposal.id), method: :delete, class: "btn btn-primary"%>
          <% end %>
          <% if current_user && (current_user?(@order.user) || current_user.admin? ) && (['Завершене'].include?(@order.status))%>
            <%= link_to "Написати відгук", new_response_path(proposal_id: proposal.id, user_id: proposal.user_id), class: "btn btn-primary" %>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</li> 

<div class="row">
  <div class="col-md-1">

  </div>
  <div class="col-md-8">

  </div>
  <div class="col-md-3">
    
  </div>
</div>

app/views/proposals/_proposal_form.html.erb
<%= form_with(model: @proposal, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
  <%= f.label :content, 'Повідомлення' %>
  <%= f.text_area :content %>

  <%= f.label :duedate, 'Дата завершення' %>
  <%= f.datetime_select :duedate, class: 'form-control'  %>

  <%= f.label :price, 'Ціна ₴' %>
  <%= f.text_field :price, type: "number", style: "width: 90%; margin-right:20px;" %>
  

  <%= f.hidden_field :order_id %>

  <%= f.submit yield(:text_button), class: "btn btn-success" %>
<% end %>

app/views/proposals/edit.html.erb
<% provide(:title, 'Редагувати заявку') %>
<% provide(:text_button, 'Змінити') %>

<div class="proposal">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">      
      <h1>Редагування даних заявки</h1>
      <%= render 'proposal_form' %>
    </div>
  </div>
</div>

app/views/proposals/new.html.erb
<% provide(:title, 'Створити заявку') %>
<% provide(:text_button, 'Створити') %>

<div class="create_order">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">      
      <h1>Створити заявку</h1>

      <%= render 'proposal_form'%>
    </div>
  </div>
</div>