config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/index', to: 'static_pages#index'
  get '/home', to: 'static_pages#home'
  get '/howitswork', to: 'static_pages#howitswork'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  get 'users/:id/orders' => 'users#orders', :as => :user_orders
  get 'users/:id/proposals' => 'users#proposals', :as => :user_proposals
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :categories
  resources :orders
  resources :proposals
  delete 'choose_proposal' => 'proposals#choose_proposal', :as => :choose_proposal
  patch '/orders/:id/finish_order' => 'orders#finish_order', :as => :finish_order
  # resources :responses, only: [:new, :create]
  resources :responses
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="social">
      <a href="#">Facebook</a>
      <a href="#">Instagram</a>
      <a href="#">YouTube</a>
    </div>
    <div class="info">
      <a href="https://github.com/mmarusyk" style="color:#EDF5E1;">GoWork Website 2020</a>
    </div>
    <div class="links">
      <%= link_to 'Як це працює', howitswork_path %>
      <%= link_to 'Про нас', about_path %>
      <%= link_to 'Допомога', help_path %>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-3 col-sm-3">
        <a class="logo" href="/">
          <div class="logo_img">
            <%= image_tag('icons/logo.png', alt: "logo_img", class: "logo_img" ) %></div>
          <div class="logo_title">GoWork</div>
        </a>
      </div>
      <div class="col-lg-9 col-md-9 col-sm-9">
        <ul class="menu">
          <% if logged_admin? %>
          <li class="menu_item"> <%= link_to 'Категорії', categories_path, class: "menu_link" %> </li>
          <% end %>
          <% if logged_in? %>
          <li class="menu_item"> <%= link_to 'Користувачі', users_path, class: "menu_link" %> </li>
          <li class="menu_item"> <%= link_to 'Замовлення', orders_path, class: "menu_link" %> </li>
          <li class="menu_item"> <%= link_to 'Заявки', user_proposals_path(current_user), class: "menu_link" %> </li>
          <li class="menu_item">
            <%= link_to "Профіль", current_user, class: "menu_link" %>
          </li>
          <li class="menu_item">
            <%= link_to "Налаштування", edit_user_path(current_user), class: "menu_link" %>
          </li>
          <li class="menu_item">
            <%= link_to "Вийти", logout_path, method: :delete, class: "menu_link" %>
          </li>
          <% else %>
          <li class="menu_item"><%= link_to 'Як це працює', howitswork_path, class: "menu_link" %></li>
          <li class="menu_item"><%= link_to 'Про нас', about_path, class: "menu_link" %></li>
          <li class="menu_item"><%= link_to 'Допомога', help_path, class: "menu_link" %></li>
          <li class="menu_item"><%= link_to 'Увійти', login_path, class: "menu_link" %></li>
          <li class="menu_item"><%= link_to 'Реєстрація', signup_path, class: "menu_link" %></li>
          <li class="menu_item"><%= link_to 'Додати замовлення', login_path, class: "menu_link add_order" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= full_title yield(:title) %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> 
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <div class="container">
  <%= debug(params) if Rails.env.development? %> 
  </div>
</body>

</html>